//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.StringCultures.Descriptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler.StringCultures.Descriptions.descriptions", typeof(descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every day {0} {1}.
        /// </summary>
        public static string DailyDesc {
            get {
                return ResourceManager.GetString("DailyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0} between {1} and {2}.
        /// </summary>
        public static string EveryDayQuote {
            get {
                return ResourceManager.GetString("EveryDayQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of every {0} months.
        /// </summary>
        public static string MonthlyDateQuote {
            get {
                return ResourceManager.GetString("MonthlyDateQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of every {1} months.
        /// </summary>
        public static string MonthlyDayQuote {
            get {
                return ResourceManager.GetString("MonthlyDayQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs the {0} {1} {2}.
        /// </summary>
        public static string MonthlyDesc {
            get {
                return ResourceManager.GetString("MonthlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {0}.
        /// </summary>
        public static string OnceDayQuote {
            get {
                return ResourceManager.GetString("OnceDayQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs once.Schedule will be used on {0} at {1} {2}.
        /// </summary>
        public static string OnceDesc {
            get {
                return ResourceManager.GetString("OnceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting on {0}.
        /// </summary>
        public static string StartingOn {
            get {
                return ResourceManager.GetString("StartingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every {0} {1} {2}.
        /// </summary>
        public static string WeeklyDesc {
            get {
                return ResourceManager.GetString("WeeklyDesc", resourceCulture);
            }
        }
    }
}
